/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
"use client";
import { useSearchParams, useParams } from "next/navigation";
import { forwardRef, Fragment, Suspense } from "react";
import { useClutchStore, useClutchInstanceContext, useClutchInstanceStore, useClutchComponentStore, useClutchComponentContext, ClutchInstanceContextProvider } from "clutch";
import cx from "classnames";
import CarouselIndicator from "@clutch-marketplace/clutch.clutch-elements/dist/components/Carousel/CarouselIndicator.js";
import { useDeepEqual, serialize } from "../../../_debug/helpers";
import { DebugReports, DebugInstance, DebugInstanceErrorWrapper } from "../../../_debug/components";
import ClutchData1739_109 from "./_data/ClutchData1739_109";
import styles from "./styles.module.css";
function ClientBindWrapper({ vars, ...props }, ref) {
    const clutchStore = useClutchStore(useDeepEqual((state)=>{
        const result = {
            states: {}
        };
        if (state?.states?.['1739_79'] && 'scrollSnapList' in state?.states?.['1739_79']) {
            result.states['1739_79'] = {
                ...result.states?.['1739_79'],
                scrollSnapList: state?.states?.['1739_79']?.scrollSnapList
            };
        }
        return result;
    }));
    const instanceStore = {
        ...useClutchInstanceStore(useDeepEqual((state)=>{
            const result = {
                states: {}
            };
            if (state?.states?.['1739_79'] && 'scrollSnapList' in state?.states?.['1739_79']) {
                result.states['1739_79'] = {
                    ...result.states?.['1739_79'],
                    scrollSnapList: state?.states?.['1739_79']?.scrollSnapList
                };
            }
            return result;
        }), "1739_79")
    };
    const componentStore = useClutchComponentStore(useDeepEqual((state)=>{
        const result = {
            states: {}
        };
        if (state?.states?.['1739_79'] && 'scrollSnapList' in state?.states?.['1739_79']) {
            result.states['1739_79'] = {
                ...result.states?.['1739_79'],
                scrollSnapList: state?.states?.['1739_79']?.scrollSnapList
            };
        }
        return result;
    }));
    const componentContext = useClutchComponentContext();
    const instanceContext = useClutchInstanceContext();
    const params = useParams();
    const searchParams = Object.fromEntries(useSearchParams().entries());
    const reports = [
        {
            type: 1,
            vars: serialize(vars)
        }
    ];
    return (<><DebugReports debug-reports={reports}>{reports.push({
        type: 2,
        id: "1739_89"
    }) && (instanceStore?.states?.["1739_79".replace((componentContext?.rootInstances || []).join('#') + '#', '')] ??       componentStore?.states?.["1739_79".replace((componentContext?.rootInstances || []).join('#') + '#', '')] ??       clutchStore.states?.[Array.from(new Set([...(componentContext?.rootInstances || []), ..."1739_79".split('#')])).join('#')] ??       clutchStore.states?.["1739_79"])?.scrollSnapList?.map((item, index)=>{
        const newVars = {
            "1739_89": {
                item,
                index
            }
        };
        const prevVars = vars;
        {
            const vars = {
                ...prevVars,
                ...newVars
            };
            const reports = [
                {
                    type: 1,
                    vars: serialize(newVars)
                }
            ];
            return <DebugInstance debug-id="1739_89" debug-parent="1739_88" debug-loop={index} key={index}><DebugReports debug-reports={reports}><Fragment key={index}><ClutchInstanceContextProvider instanceId="1739_90" component={CarouselIndicator}><DebugInstanceErrorWrapper data-d="1739_89#1739_90"><DebugInstance debug-id="1739_90" debug-parent="1739_89"><CarouselIndicator><DebugInstanceErrorWrapper data-d="1739_90#1739_91"><div className={cx(styles.clt_1739_91, "clt_1739_91")} data-d="1739_90#1739_91"/></DebugInstanceErrorWrapper></CarouselIndicator></DebugInstance></DebugInstanceErrorWrapper></ClutchInstanceContextProvider><DebugInstanceErrorWrapper data-d="1739_89#1739_109"><DebugInstance debug-id="1739_109" debug-parent="1739_89"><Suspense key="bd50ebe15727db63b038fc4c06172d69"><ClutchData1739_109 {...props} params={params} searchParams={searchParams} vars={vars}/></Suspense></DebugInstance></DebugInstanceErrorWrapper></Fragment></DebugReports></DebugInstance>;
        }
    })}</DebugReports></>);
}
export default forwardRef(ClientBindWrapper);
