/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import cx from "classnames";
import { ClutchContextProvider } from "../../clutch/components/ClutchContext";
import { ClutchHelpers } from "../../clutch/components/ClutchHelpers";
import { ClutchActions } from "../../clutch/components/ClutchActions";
import fontsClassName from "../../fonts";
import "../../variables.css";
import "../../global.css";
import "../../classes.css";
import { ClutchNextInspector } from "../_debug/components";
import styles from "./layout-styles.module.css";
const cltPluginsHooks = [].filter(Boolean);
export async function generateMetadata() {
    const baseUrl = process?.env?.NEXT_PUBLIC_WEBSITE_URL;
    return {
        metadataBase: new URL(baseUrl)
    };
}
export default async function RootLayout({
    params,
    searchParams,
    ...props
}) {
    const vars = {};
    return (<html lang="en" className={fontsClassName} suppressHydrationWarning style={{
        scrollBehavior: "initial"
    }}><head/><body data-d="v221_3" className={cx(styles.clt_v221_3, "clt_v221_3")} style={{
        scrollBehavior: "initial"
    }}><script dangerouslySetInnerHTML={{
        __html: "window.onerror = function (message) { window.parent.postMessage(message, '*'); }"
    }}/><ClutchNextInspector/><ClutchHelpers/><ClutchActions/><ClutchContextProvider>{props.children}</ClutchContextProvider></body></html>);
}
