/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import { Bricolage_Grotesque } from "next/font/google";
let fontsClassName = "";
const bricolage_grotesque = Bricolage_Grotesque({
    variable: "--fonts-bricolage_grotesque",
    weight: [
        "200",
        "300",
        "400",
        "500",
        "600",
        "700",
        "800"
    ],
    subsets: [
        "latin"
    ],
    style: [
        "normal"
    ]
});
fontsClassName += ` ${bricolage_grotesque.variable}`;
export default fontsClassName;
