/* THIS FILE WAS AUTOGENERATED BY CLUTCH. DO NOT EDIT. */
import { REST } from "@clutch-marketplace/clutch.rest/dist/actions/REST.js";
import { REST as REST1 } from "@clutch-marketplace/clutch.rest/dist/queries/REST.js";
import { GraphQL } from "@clutch-marketplace/clutch.graphql/dist/actions/GraphQL.js";
import { GraphQL as GraphQL1 } from "@clutch-marketplace/clutch.graphql/dist/queries/GraphQL.js";
import { sendGoogleTagManagerEvent, sendGoogleAnalyticsEvent } from "@clutch-marketplace/clutch.google-analytics/dist/actions/google.js";
import { getMedia, getMediaItemBySlug, getMediaItemById } from "@clutch-marketplace/clutch.wordpress/dist/queries/media.js";
import { getUsers, getUserBySlug, getUserById } from "@clutch-marketplace/clutch.wordpress/dist/queries/users.js";
import { getTaxonomyTerms, getTaxonomyTermBySlug, getTaxonomyTermById } from "@clutch-marketplace/clutch.wordpress/dist/queries/taxonomies.js";
import { getTags, getTagBySlug, getTagById } from "@clutch-marketplace/clutch.wordpress/dist/queries/tags.js";
import { getCategories, getCategoryBySlug, getCategoryById } from "@clutch-marketplace/clutch.wordpress/dist/queries/categories.js";
import { search } from "@clutch-marketplace/clutch.wordpress/dist/queries/search.js";
import { getPosts, getPostBySlug, getPostById } from "@clutch-marketplace/clutch.wordpress/dist/queries/posts.js";
import { getPages, getPageBySlug, getPageById, getFrontPage } from "@clutch-marketplace/clutch.wordpress/dist/queries/pages.js";
import { getMenu } from "@clutch-marketplace/clutch.wordpress/dist/queries/menus.js";
import { navigate, goBack, goForward, refresh, replace } from "@clutch-marketplace/clutch.actions/dist/actions/navigation.js";
export const serverFunctions = {
    "@clutch-marketplace/clutch.rest": {
        "/dist/actions/REST.ts": {
            "REST": REST
        },
        "/dist/queries/REST.ts": {
            "REST": REST1
        }
    },
    "@clutch-marketplace/clutch.graphql": {
        "/dist/actions/GraphQL.ts": {
            "GraphQL": GraphQL
        },
        "/dist/queries/GraphQL.ts": {
            "GraphQL": GraphQL1
        }
    },
    "@clutch-marketplace/clutch.google-analytics": {
        "/dist/actions/google.ts": {
            "sendGoogleTagManagerEvent": sendGoogleTagManagerEvent,
            "sendGoogleAnalyticsEvent": sendGoogleAnalyticsEvent
        }
    },
    "@clutch-marketplace/clutch.wordpress": {
        "/dist/queries/media.ts": {
            "getMedia": getMedia,
            "getMediaItemBySlug": getMediaItemBySlug,
            "getMediaItemById": getMediaItemById
        },
        "/dist/queries/users.ts": {
            "getUsers": getUsers,
            "getUserBySlug": getUserBySlug,
            "getUserById": getUserById
        },
        "/dist/queries/taxonomies.ts": {
            "getTaxonomyTerms": getTaxonomyTerms,
            "getTaxonomyTermBySlug": getTaxonomyTermBySlug,
            "getTaxonomyTermById": getTaxonomyTermById
        },
        "/dist/queries/tags.ts": {
            "getTags": getTags,
            "getTagBySlug": getTagBySlug,
            "getTagById": getTagById
        },
        "/dist/queries/categories.ts": {
            "getCategories": getCategories,
            "getCategoryBySlug": getCategoryBySlug,
            "getCategoryById": getCategoryById
        },
        "/dist/queries/search.ts": {
            "search": search
        },
        "/dist/queries/posts.ts": {
            "getPosts": getPosts,
            "getPostBySlug": getPostBySlug,
            "getPostById": getPostById
        },
        "/dist/queries/pages.ts": {
            "getPages": getPages,
            "getPageBySlug": getPageBySlug,
            "getPageById": getPageById,
            "getFrontPage": getFrontPage
        },
        "/dist/queries/menus.ts": {
            "getMenu": getMenu
        }
    },
    "@clutch-marketplace/clutch.actions": {
        "/dist/actions/navigation.ts": {
            "navigate": navigate,
            "goBack": goBack,
            "goForward": goForward,
            "refresh": refresh,
            "replace": replace
        }
    }
};
